library(GenomicRanges)

# Specify the directory path of my narrowPeak files
directory <- "/Users/yulongqiu/Desktop/Biostats/Master_Thesis/Peaks_bysample/By_sample_Narrowpeaks"
# Gets the file names of all narrowPeak files in the directory
files <- list.files(path = directory, pattern = "*.narrowPeak", full.names = TRUE)


# Create an empty list to store the GRanges objects generated by each file
granges_list <- list()
# Use a loop to iterate through each file and convert it to a GRanges object
for (file in files) {
df <- read.table(file = file, 
                   col.names = c("chr", "start", "end", "name", "score", "strand", 
                                 "fold_change", "neg_log10pvalue_summit", 
                                 "neg_log10qvalue_summit", "relative_summit_position"))
  # Convert each file to Grange object
  peaks <- makeGRangesFromDataFrame(df = df, keep.extra.columns = TRUE)
  granges_list[[basename(file)]] <- peaks
}
#print Granges_list
print(granges_list)

combined.granges <- unlist(GRangesList(granges_list))
# Use reduce to combine
combined.peaks <- reduce(x = combined.granges)
print(combined.peaks)

#save file as rdata format
save(combined.peaks, file = "/Users/yulongqiu/Desktop/Biostats/Master_Thesis/combined_peaks.RData")
#save file as rds format
saveRDS(combined.peaks, file = "/Users/yulongqiu/Desktop/Biostats/Master_Thesis/combined_peaks.rds")















